FROM openjdk:17
WORKDIR ~/Downloads/HamroPatro-20231016T091404Z-001/HamroPatro/blog
COPY . /Downloads/HamroPatro-20231016T091404Z-001/HamroPatro/blog/
CMD ["java","/home/kishor/Downloads/HamroPatro-20231016T091404Z-001/HamroPatro/blog/build/libs/blog-0.1.jar"]